### ISSUE TITLE
Add one environment total three added

### ISSUE THREAD

**Issue by daleqq** [gcuisinier/jenv#105]
When I add environment jdk1.7.0_79, total 3 versions are displayed:
 * 1.7
 * 1.7.0.79
 * oracle64-1.7.0.79

Is it the right result? If not, how can I remove the others?

Thanks

**Comment by Unbr8kbal** [comment]
This result is correct, i'm not the developer of jenv, however i think this was done for simplicity, since java developers usually have one version of each major version there is, so you might want to swap to java 1.7 and you'll know which version that is, so you don't want to type out 1.7.0.79 or oracle64-1.7.0.79, however if you do have more then one version of the major versions say 1.7.0.80, you will probably want to switch between the two, therefore you'll want to type 1.7.0.80 and the oracle64-X is if you also have openjdk.

**Comment by daleqq** [comment]
Get it. Thank you very much.

**Comment by gcuisinier** [comment]
I confirm that is the awaited result.
