### ISSUE TITLE
Hot to uninstall jenv

### ISSUE THREAD

**Issue by c0nscience** [gcuisinier/jenv#95]
Hi,
I looking for a way to uninstall jenv completely and revert everything to the state as before installing jenv. Is it that simple to remove .jenv folder, remove it from my zsh config and reset JAVA_HOME to the currently actual java installation ?

**Comment by gcuisinier** [comment]
Yes.
All the "magic' is enable with the modification of zsh config, so removing the line into .zshrc will disable jenv.

After, removing .jenv and jenv installation directory could be done clean the machine.

**Comment by henryzolo** [comment]
I use brew uninstall jenv, and reset JAVA_HOME.
However, when I use java -version command in terminal, the return shows

> line 21: /usr/local/Cellar/jenv/0.4.4/libexec/libexec/jenv: No such file or directory

Also, when I install jenv again, it looks like previous added JDK version are still in jenv versions.

I am kind of a newbie, can you show me how to remove it completely as I want to re-install it.
The reason I want to re-install it is because the switch doesn't work for me anymore. Once I switch it to JAVA 9, it sticks there forever.

**Comment by MarkusBansky** [comment]
Hi, chaps.

I had the same issue, I had a problem with `jenv` and decided to clearly uninstall it from my **macOS Big Sur**, I think this would be the same process for other versions of **macOS**, so I decided to post my approach to this.

1. Run the **brew** command to uninstall it: `brew uninstall jenv`. At this point you should not have the executables, but still have some scripts referencing `jenv` left on your system.
2. I am using **iTerm2** with **zsh**, so I had to remove part of the code in my `~/.zshrc` file, (you can remove relevant code in the `~/.bash_profile` file), the code to be removed is something like this:
```
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"
```
3. Remove the `.jenv` folder: `rm -rf .jenv`

I hope this is it, this fixed all problems for me and I was able to reinstall in from scratch.
